server:
  port: 9999

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Mysql
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console
